/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('./damagedHelmet/DamagedHelmet.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow={props.shadows}
        receiveShadow={props.shadows}
        geometry={nodes['node_damagedHelmet_-6514'].geometry}
        material={materials.Material_MR}
        rotation={[Math.PI / 2, 0, 0]}
        material-envMap={props.envMap}
        material-envMapIntensity={props.envMapIntensity}
      />
    </group>
  );
}

useGLTF.preload('./damagedHelmet/DamagedHelmet.gltf');
